#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Minimal stage-0 verification for the OpenSim Python IK path:

TRC -> TimeSeriesTableVec3 -> MarkersReference -> InverseKinematicsSolver

This script is intentionally conservative. It prefers demo artifacts already
generated by the offline pipeline, falls back to the packaged simple model, and
tries a small set of constructor overloads that are commonly exposed through
the SWIG Python bindings.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable, List, Sequence, Tuple

import opensim as osim


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Verify OpenSim Python IK API path.")
    parser.add_argument("--model", type=Path, help="Path to an .osim model.")
    parser.add_argument("--trc", type=Path, help="Path to a .trc marker file.")
    return parser.parse_args()


def repo_pose2sim_dir() -> Path:
    return Path(__file__).resolve().parents[1]


def pick_default_model(pose2sim_dir: Path) -> Path:
    demo_kinematics_dir = pose2sim_dir / "Demo_SinglePerson" / "kinematics"
    demo_models = sorted(demo_kinematics_dir.glob("*.osim"))
    if demo_models:
        return demo_models[0]
    return pose2sim_dir / "OpenSim_Setup" / "Model_Pose2Sim_simple.osim"


def pick_default_trc(pose2sim_dir: Path) -> Path:
    candidates = [
        pose2sim_dir / "Demo_SinglePerson" / "pose-3d" / "Demo_SinglePerson_1-96_filt_butterworth_LSTM.trc",
        pose2sim_dir / "Demo_SinglePerson" / "pose-3d" / "Demo_SinglePerson_1-96_filt_butterworth.trc",
        pose2sim_dir / "Demo_SinglePerson" / "pose-3d" / "Demo_SinglePerson_1-95.trc",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    raise FileNotFoundError("Could not find a demo TRC file to validate against.")


def load_table(trc_path: Path) -> osim.TimeSeriesTableVec3:
    table = osim.TimeSeriesTableVec3(str(trc_path))
    labels = list(table.getColumnLabels())
    times = list(table.getIndependentColumn())
    print(f"[ok] Loaded TRC table: {trc_path}")
    print(f"     rows={table.getNumRows()} cols={len(labels)}")
    print(f"     labels(sample)={labels[:6]}")
    print(f"     time_range=({times[0]:.4f}, {times[-1]:.4f})")
    return table


def build_marker_weights(labels: Sequence[str]) -> osim.SetMarkerWeights:
    weights = osim.SetMarkerWeights()
    for label in labels:
        weights.cloneAndAppend(osim.MarkerWeight(str(label), 1.0))
    print(f"[ok] Built marker weights for {weights.getSize()} markers.")
    return weights


def build_markers_reference(
    table: osim.TimeSeriesTableVec3,
    weights: osim.SetMarkerWeights,
) -> tuple[osim.MarkersReference, str]:
    candidates = [
        ("MarkersReference(table, weights)", lambda: osim.MarkersReference(table, weights)),
        (
            "MarkersReference(table, weights, Units.Meters)",
            lambda: osim.MarkersReference(table, weights, osim.Units(osim.Units.Meters)),
        ),
    ]
    last_error = None
    for label, factory in candidates:
        try:
            return factory(), label
        except Exception as exc:  # pragma: no cover - debugging path
            last_error = exc
            print(f"[warn] {label} failed: {type(exc).__name__}: {exc}")
    raise RuntimeError(f"Could not construct MarkersReference: {last_error}")


def build_ik_solver(
    model: osim.Model,
    markers_ref: osim.MarkersReference,
) -> tuple[osim.InverseKinematicsSolver, str]:
    coord_refs = osim.SimTKArrayCoordinateReference()
    candidates = [
        (
            "InverseKinematicsSolver(model, markers_ref, coord_refs)",
            lambda: osim.InverseKinematicsSolver(model, markers_ref, coord_refs),
        ),
        (
            "InverseKinematicsSolver(model, markers_ref, coord_refs, 1.0)",
            lambda: osim.InverseKinematicsSolver(model, markers_ref, coord_refs, 1.0),
        ),
        (
            "InverseKinematicsSolver(model, markers_ref, coord_refs, False)",
            lambda: osim.InverseKinematicsSolver(model, markers_ref, coord_refs, False),
        ),
    ]
    last_error = None
    for label, factory in candidates:
        try:
            return factory(), label
        except Exception as exc:  # pragma: no cover - debugging path
            last_error = exc
            print(f"[warn] {label} failed: {type(exc).__name__}: {exc}")
    raise RuntimeError(f"Could not construct InverseKinematicsSolver: {last_error}")


def preview_coordinates(model: osim.Model, limit: int = 8) -> List[str]:
    coord_set = model.getCoordinateSet()
    names = [coord_set.get(i).getName() for i in range(min(coord_set.getSize(), limit))]
    print(f"[info] Coordinate sample: {names}")
    return names


def main() -> None:
    args = parse_args()
    pose2sim_dir = repo_pose2sim_dir()

    model_path = (args.model or pick_default_model(pose2sim_dir)).resolve()
    trc_path = (args.trc or pick_default_trc(pose2sim_dir)).resolve()

    if not model_path.exists():
        raise FileNotFoundError(f"Model not found: {model_path}")
    if not trc_path.exists():
        raise FileNotFoundError(f"TRC not found: {trc_path}")

    print(f"[info] OpenSim: {osim.GetVersionAndDate()}")
    print(f"[info] Model path: {model_path}")
    print(f"[info] TRC path:   {trc_path}")

    geometry_dir = pose2sim_dir / "OpenSim_Setup" / "Geometry"
    if geometry_dir.exists():
        osim.ModelVisualizer.addDirToGeometrySearchPaths(str(geometry_dir))

    model = osim.Model(str(model_path))
    state = model.initSystem()
    print("[ok] Model loaded and system initialized.")
    print(f"[info] marker_count_in_model={model.getMarkerSet().getSize()}")
    preview_coordinates(model)

    table = load_table(trc_path)
    labels = list(table.getColumnLabels())
    weights = build_marker_weights(labels)

    markers_ref, markers_ref_ctor = build_markers_reference(table, weights)
    print(f"[ok] MarkersReference constructed via {markers_ref_ctor}")

    solver, solver_ctor = build_ik_solver(model, markers_ref)
    print(f"[ok] InverseKinematicsSolver constructed via {solver_ctor}")

    if hasattr(solver, "setAccuracy"):
        solver.setAccuracy(1e-3)
        print("[ok] Solver accuracy set to 1e-3.")

    if hasattr(solver, "setAdvanceTimeFromReference"):
        solver.setAdvanceTimeFromReference(False)
        print("[ok] Solver set to use caller-controlled time.")

    times = list(table.getIndependentColumn())
    state.setTime(float(times[0]))
    solver.assemble(state)
    print("[ok] assemble(state) succeeded on first frame.")

    print(f"[info] num_markers_in_use={solver.getNumMarkersInUse()}")
    if solver.getNumMarkersInUse() > 0 and hasattr(solver, "computeCurrentMarkerError"):
        first_marker_name = model.getMarkerSet().get(0).getName()
        print(f"[info] first_marker_name={first_marker_name}")
        print(f"[info] first_marker_error={solver.computeCurrentMarkerError(first_marker_name):.6f}")

    if len(times) > 1 and hasattr(solver, "track"):
        state.setTime(float(times[1]))
        solver.track(state)
        print("[ok] track(state) succeeded on second frame.")

    print("\n[pass] OpenSim Python IK API path is working at the basic level.")


if __name__ == "__main__":
    main()
